FROM amazoncorretto:11
ADD target/sample-bicycle-booking-app-1.0.0-SNAPSHOT.jar sample-bicycle-booking-app-1.0.0-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "sample-bicycle-booking-app-1.0.0-SNAPSHOT.jar"]