spring:
  datasource:
    url: jdbc:mysql://bicycle.ct2hi1fyhygp.us-east-1.rds.amazonaws.com:3306/bicycle
    password: Ravi1646
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update